kind: HorizontalPodAutoscaler
apiVersion: autoscaling/v2beta2
metadata:
  name: hpa-resource-metrics-memory
  namespace: {yourNameSpace}
spec:
  scaleTargetRef:
    kind: Deployment
    name: {yourDeploymentName}
    apiVersion: apps/v1
  minReplicas: 1
  maxReplicas: 10
  metrics:
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 30
status:{}
